spring:
  application:
    name: PSproject
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    spring:
      mvc:
        view:
          prefix: /WEB_INF/jsp/
          suffix: .jsp

    jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
