spring:
  application:
    name: PSproject
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    spring:
      mvc:
        view:
          prefix: /WEB-INF/jsp/
          suffix: .jsp
        format:
          date: iso
          dateTime: iso

jpa:
  properties.hibernate:
    show_sql: true
    format_sql: true
    hbm2ddl.auto: validate
  open-in-view: false


